#Site settings

title: Alberto EA Uribe Website
email: alberto.alvarez@mau.se
twitter_username: aeau
github_username: aeau

name: Alberto Alvarez, Assistant Professor
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-minimal
highlighter: rouge

tags: 

collections:
  - indThesis
  - papers